### ISSUE TITLE
The practical impact

### ISSUE THREAD

**Issue by adastreamer** [kudelskisecurity/ecdsa-polynomial-nonce-recurrence-attack#2]
Hello,

I read your paper at iacr.org, thank you for detailed explanation, but I have a question: what is a practical impact of your “new attack” if all nonces are generated in a random way?

I mean this is a pretty obvious that if nonces are in a known sequence, secrets might be revealed, just trying to understand the full picture of your method. Are you like trying to understand the relation for given nonces and solve the matrix of equations, or you’re analyzing nonces using known sequences?

Thank you.

**Comment by amietn** [comment]
Hello @adastreamer . Thank you for your interest in our attack.

If the nonces are all unique and generated uniformly at random, then the attack does not apply, as mentioned in the paper.

We make a hypothesis that the nonces were generated using a recurrence relation. That means, a nonce depends in a polynomial way on the previous nonce.
Under this hyptothesis, we solve the equations to find candidate values for the private key. We check whether this private key is correct.
If the nonces were indeed generated according to our hypothesis, then the attack will work. Otherwise it won't.
